config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  root to: 'articles#index'
  resources :articles
  resources :users
  resources :sessions

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: {message: "cannot be blank."}
  validates :body, presence: {message: "cannot be blank."}
  
  default_scope { order(created_at: :desc)}
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
    
  validates_uniqueness_of :email
  validates :password, :length => {minimum: 8, message: "must be at least 8 characters."}
  
  def minimum_password_length()
    length = 8
  end
  
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Sign up or sign in to complete this action." if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, except: [:index, :show]
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = current_user.articles.build(article_params)#associates current user id with article, previously was @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article successfully created."
      redirect_to articles_path
    else 
      flash.now[:danger] = "There was an error."
      #render new template again
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article has been updated."
      redirect_to @article
    else
      flash.now[:danger] = "Article has not been updated."
      render :edit
    end
  end
  
  def show
  end
  
  def destroy
    if @article.destroy
      flash[:success] = "Article has been deleted."
      redirect_to articles_path
    end
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
  
  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "You have signed in."
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
      redirect_to root_url, notice: "You have successfully signed out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "You have signed up successfully."
    else
      render "new"
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <% if @article.errors.any? %>
      <div class="panel panel-danger col-md-offset-1">
        <div class="panel-heading">
          <h2 class="panel-title">
          <%= pluralize(@article.errors.count, "error") %>
          prohibited this article from being saved:</h2>
          <div class="panel-body">
            <ul>
              <% @article.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <div class="control-label col-md-1">
        <%= f.label :title %>
      </div>
      <div class="col-md-11">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-1">
        <%= f.label :body %>
      </div>
      <div class="col-md-11">
        <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Body of article" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-f-1 col-md-11">
        <%= f.submit class: "btn btn-primary btn-lg pull-right" %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h3 class="text-center">Edit an Article</h3>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>List of all Articles</h1>

<%= link_to "New Article", new_article_path, class: "btn btn-default btn-lg", id: "new-article-btn" %>

<% @articles.each do |article| %>
  <div class="well well-lg">
    <div class="article-title">
      <%= link_to article.title, article_path(article) %>
    </div>
    <div class="article-body">
      <%= truncate(article.body, length: 500) %>
    </div>
    <div class="author">
      <% if article.user %>
      <small>Created by: <%= article.user.email %></small>
      <% end %>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h3 class="text-center">Adding New Article</h3>
<%= render 'form' %>

app/views/articles/show.html.erb
<article class="detail-article">
  <h1 class="article-detail-title">
    <%= @article.title %>
  </h1>
  <div class="glyphicon glyphicon-calendar" id="article-date">
    <%= @article.created_at.strftime("%b %d, %y") %>
  </div>
  <div class="article-body">
    <%= @article.body %>
  </div>
  
  <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-primary btn-lg btn-space" %>
  <%= link_to "Delete Article", article_path(@article), method: :delete,
        class: "btn btn-danger btn-lg btn-space",
        data: {confirm: "Are you sure?"} %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogAppUdemy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/header" %>
  <%= render "shared/main" %>
  <%= render "shared/footer" %>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 text-center">
      <footer role="contentinfo">
        <p><small>Made at <a href="http://udemy.com" target="_blank">Udemy.com</a></small></p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Blog App", root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse" id="example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to "Authors", "#" %>
          </li>
          <% if current_user %>
            <li>
            <% if false %>
            <%= link_to "Log out", session_path("current"), method: :delete %>
            <% end %>
            <%= link_to "Log out", logout_path %>
          </li>
            <div class="navbar-right">
              <p class="navbar-text">You are signed in as <%= "#{current_user.email}" %></p>
            </div>
          <% else %>
          <li>
            <% if false %>
            <%= link_to "Sign up", new_user_path %>
            <% end %>
            <%= link_to "Sign up", signup_path %>
          </li>
          <li>
            <% if false %>
            <%= link_to "Sign in", new_session_path %>
            <% end %>
            <%= link_to "Sign in", login_path %>
          </li>
          <% end %> 
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="col-md-8">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href='#' class="close" data-dismiss="alert" &#215;></a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    
    <div class="col-md-4">
      <%= yield :sidebar %>
    </div>
  </div>
</div>
</div>

app/views/users/new.html.erb
<h2 class="text-center">Sign Up</h2>
<div class="row">
  <%= form_for @user, :html => {class: "form-horizontal", role: "form"} do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="control-label col-md-3">
      <%= f.label :email %>
    </div>
    <div class="col-md-9">
      <%= f.text_field :email, class: "form-control", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-md-3">
      <%= f.label :password %>
    </div>
    <div class="col-md-9">
      <%= f.password_field :password, class: "form-control", autocomplete: "off" %>
      <% if @user.minimum_password_length %>
        <em>(<%= @user.minimum_password_length %> characters minimum)</em>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-md-3">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-md-9">
      <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "off" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-3 col-md-9">
      <%= f.submit "Sign up", class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>
  <div class="form-group">
    <div class="col-md-offset-3 col-md-9">
      <%= link_to "Log in", login_path %>
    </div>
  </div>
</div>